version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: willian
  MYSQL_PASSWORD: deliver@2021
  MYSQL_DATABASE: deliver
  NODE_APP_SERVER_PORT: 4000

services:
  api:
    build: ./api
    container_name: grupoa_api_fullstack_challenge    
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql-db
    volumes:
      - /usr/src/app/api/node_modules
    ports:
      - 4000:4000    
    command: npm run serve
  ui:
    build:
      context: ./ui
    container_name: grupoa_ui_fullstack_challenge
    environment:
      <<: *common-variables
    volumes:
      - /usr/src/app/ui/node_modules
    ports:
      - 8080:8080
    links:
      - api
    command: npm run serve