version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: grupoa
  MYSQL_PASSWORD: grupoa@2021
  MYSQL_DATABASE: edtech
  NODE_APP_SERVER_PORT: 3333

services:
  grupo-a-mysql-db:
    image: mysql:5.7
    container_name: grupo-a-mysql-db
    environment:
      <<: *common-variables
      MYSQL_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: root
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  grupo-a-api:
    build: ./api
    container_name: grupo-a-api
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql-db
    volumes:
      - /usr/src/app/api/node_modules
    ports:
      - 3333:3333
    links:
        - grupo-a-mysql-db
    depends_on:
      - grupo-a-mysql-db
    command: bash -c 'while !</dev/tcp/grupo-a-mysql-db/3306; do sleep 1; done; npm run dev'
  grupo-a-ui:
    build:
      context: ./ui
    container_name: grupo-a-ui
    environment:
      <<: *common-variables
    volumes:
      - /usr/src/app/ui/node_modules
    ports:
      - 8080:8080
    links:
      - grupo-a-api
    command: npm run serve